const String APP_NAME = "我地.佳招";
const String SMS_CODE_DIALOG_TITLE = "Enter SMS Code";
const String SMS_CODE_DIALOG_BUTTON_TEXT = "Verify";
const String REG_BUTTON_TEXT = "Register";
const String REG_USERNAME_HINT_TEXT = "Enter Username";
const String REG_PHONE_NUMBER_HINT_TEXT = "Enter Phone number";
const String REG_ADDRESS_HINT_TEXT = "Home / Office Address (Optional)";
const String REG_FAILED_TO_CREATE_USER_TEXT = "Failed to create a user";
const String DEFAULT_AVATAR_IMAGE_PATH = "assets/images/default-avatar.jpg";
